#ifndef DEFINES_H
#define DEFINES_H

#define MAX_BATTERY_VOLTAGE 11.1f
#define FLOAT_MULTIPLIER 1

#define COMMAND_MOTOR_LEFT_SETSPEED 1
#define COMMAND_MOTOR_LEFT_SETTHROTTLE 2
#define COMMAND_MOTOR_RIGHT_SETSPEED 3
#define COMMAND_MOTOR_RIGHT_SETTHROTTLE 4
#define COMMAND_MOTOR_SETMOTORMODE 5

#endif