#ifndef DEFINES_H
#define DEFINES_H

#define MAX_BATTERY_VOLTAGE 11.1f
#define FLOAT_MULTIPLIER 1000

#define COMMAND_MOTOR_LEFT_SETSPEED 1
#define COMMAND_MOTOR_LEFT_SETTHROTTLE 2
#define COMMAND_MOTOR_LEFT_SETKP 3
#define COMMAND_MOTOR_LEFT_SETKI 4
#define COMMAND_MOTOR_LEFT_SETKD 5
#define COMMAND_MOTOR_LEFT_SETMODE 6
#define COMMAND_MOTOR_RIGHT_SETSPEED 7
#define COMMAND_MOTOR_RIGHT_SETTHROTTLE 8
#define COMMAND_MOTOR_RIGHT_SETKP 9
#define COMMAND_MOTOR_RIGHT_SETKI 10
#define COMMAND_MOTOR_RIGHT_SETKD 11
#define COMMAND_MOTOR_RIGHT_SETMODE 12
#define COMMAND_UPDATE_SETFREQUENCY 13
#define COMMAND_NAVIGATION_SETMODE 14
#define COMMAND_NAVIGATION_MOVE_FORWARD 15
#define COMMAND_NAVIGATION_MOVE_BACKWARD 16
#define COMMAND_NAVIGATION_MOVE_LEFT 17
#define COMMAND_NAVIGATION_MOVE_RIGHT 18
#define COMMAND_NAVIGATION_MOVE_STOP 19
#define COMMAND_BUZZER_SETSTATE 20



#endif