#ifndef PINS_H
#include "Arduino.h"

// Pinos dos Ultrassons
#define PIN_ULTRASSOUND_FRONT_ECHO A3
#define PIN_ULTRASSOUND_FRONT_TRIGGER A2
#define PIN_ULTRASSOUND_FRONT_LEFT_ECHO A5
#define PIN_ULTRASSOUND_FRONT_LEFT_TRIGGER A4
#define PIN_ULTRASSOUND_FRONT_RIGHT_ECHO A1
#define PIN_ULTRASSOUND_FRONT_RIGHT_TRIGGER A0
#define PIN_ULTRASSOUND_LEFT_ECHO 25
#define PIN_ULTRASSOUND_LEFT_TRIGGER 23
#define PIN_ULTRASSOUND_RIGHT_ECHO 53
#define PIN_ULTRASSOUND_RIGHT_TRIGGER 51
#define PIN_ULTRASSOUND_BACK_ECHO 33
#define PIN_ULTRASSOUND_BACK_TRIGGER 31
#define PIN_ULTRASSOUND_BACK_LEFT_ECHO 25
#define PIN_ULTRASSOUND_BACK_LEFT_TRIGGER 23
#define PIN_ULTRASSOUND_BACK_RIGHT_ECHO 49
#define PIN_ULTRASSOUND_BACK_RIGHT_TRIGGER 47

// Pinos dos Motores
#define PIN_MOTOR_LEFT_DIRA 9
#define PIN_MOTOR_LEFT_DIRB 8
#define PIN_MOTOR_LEFT_PWM 10
#define PIN_MOTOR_LEFT_ENCODER 2
#define PIN_MOTOR_RIGHT_DIRA 11
#define PIN_MOTOR_RIGHT_DIRB 12
#define PIN_MOTOR_RIGHT_PWM 13
#define PIN_MOTOR_RIGHT_ENCODER 3

#define PIN_BUZZER 4

#endif